// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit manually.
// Generated by contracts/script/export-abi.sh
// Chain: SidraChain (97453)
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// Chain: SidraChain (97453)
// ─────────────────────────────────────────────────────────────────────────────

export const SIDRACHAIN_CHAIN_ID = 97453 as const;

/**
 * Deployed contract addresses on Sidra Chain (Chain ID: 97453).
 */
export const CONTRACT_ADDRESSES = {
  factory: (process.env.NEXT_PUBLIC_FACTORY_ADDRESS ||
    "0xD33B40dd3a482d58C1F6a3dF8284A6ee05A378fC") as `0x${string}`,
  router: (process.env.NEXT_PUBLIC_ROUTER_ADDRESS ||
    "0x8f58131528C2F37e5221296937d8AEee3Df26E22") as `0x${string}`,
  sGold: (process.env.NEXT_PUBLIC_SGOLD_ADDRESS ||
    "0x0000000000000000000000000000000000000000") as `0x${string}`,
  sUsd: (process.env.NEXT_PUBLIC_SUSD_ADDRESS ||
    "0x0000000000000000000000000000000000000000") as `0x${string}`,
} as const;


export const SIDEX_ROUTER_ABI = [
  // ... keep the full one from contracts.ts (the uploaded file)
] as const;


export const SIDEX_FACTORY_ABI = [

] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;