#!/usr/bin/env bash
# export-abi.sh
# Extracts compiled ABIs from Foundry's out/ directory and merges them with
# deployed addresses to produce client/src/config/contracts.ts
#
# Run from the repo root:
#   bash contracts/script/export-abi.sh
#
# Prerequisites:
#   - forge build has been run (out/ must exist)
#   - out/deployed-addresses.json must exist (written by Deploy.s.sol)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$REPO_ROOT/contracts/out"
CLIENT_CONFIG="$REPO_ROOT/client/src/config/contracts.ts"

echo "── Extracting ABIs ─────────────────────────────────────────────────────"

# ── 1. Read deployed addresses ───────────────────────────────────────────────
ADDRESSES_FILE="$OUT_DIR/deployed-addresses.json"
if [[ ! -f "$ADDRESSES_FILE" ]]; then
  echo "ERROR: $ADDRESSES_FILE not found. Run the Deploy script first."
  exit 1
fi

FACTORY_ADDR=$(jq -r '.factory' "$ADDRESSES_FILE")
ROUTER_ADDR=$(jq -r '.router'  "$ADDRESSES_FILE")
CHAIN_ID=$(jq -r '.chainId'   "$ADDRESSES_FILE")

echo "Factory : $FACTORY_ADDR"
echo "Router  : $ROUTER_ADDR"
echo "ChainID : $CHAIN_ID"

# ── 2. Extract ABIs from Foundry artifacts ────────────────────────────────────
FACTORY_ABI=$(jq '.abi' "$OUT_DIR/SidExFactory.sol/SidExFactory.json")
ROUTER_ABI=$(jq  '.abi' "$OUT_DIR/SidExRouter.sol/SidExRouter.json")

# ── 3. Write contracts.ts ────────────────────────────────────────────────────
mkdir -p "$(dirname "$CLIENT_CONFIG")"

cat > "$CLIENT_CONFIG" << TYPESCRIPT
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit manually.
// Generated by contracts/script/export-abi.sh
// Chain: SidraChain (${CHAIN_ID})
// ─────────────────────────────────────────────────────────────────────────────

export const SIDRACHAIN_CHAIN_ID = ${CHAIN_ID} as const;

// ── Deployed addresses ────────────────────────────────────────────────────────
export const CONTRACT_ADDRESSES = {
  SidExFactory: "${FACTORY_ADDR}" as \`0x\${string}\`,
  SidExRouter:  "${ROUTER_ADDR}"  as \`0x\${string}\`,
} as const;

// ── ABIs ──────────────────────────────────────────────────────────────────────
export const SIDEX_FACTORY_ABI = ${FACTORY_ABI} as const;

export const SIDEX_ROUTER_ABI = ${ROUTER_ABI} as const;
TYPESCRIPT

echo ""
echo "✅  Written to $CLIENT_CONFIG"
